### ISSUE TITLE
Part12, Ch5 Lec03의 슬라이딩 세션과 리프레쉬 토큰 구현2에서 Dependency문제가 발생하고 있습니다.

### ISSUE THREAD

**Issue by neighborpil** [fresh502/fastcampus-nestjs#5]
오류는 다음과 같습니다.

[Nest] 87065  - 07/11/2024, 5:13:08 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the JwtAuthGuard (Reflector, ?, UserService). Please make sure that the argument JwtService at index [1] is available in the UserModule context.

Potential solutions:
- Is UserModule a valid NestJS module?
- If JwtService is a provider, is it part of the current UserModule?
- If JwtService is exported from a separate @Module, is that module imported within UserModule?
  @Module({
    imports: [ /* the Module containing JwtService */ ]
  })

Error: Nest can't resolve dependencies of the JwtAuthGuard (Reflector, ?, UserService). Please make sure that the argument JwtService at index [1] is available in the UserModule context.

Potential solutions:
- Is UserModule a valid NestJS module?
- If JwtService is a provider, is it part of the current UserModule?
- If JwtService is exported from a separate @Module, is that module imported within UserModule?
  @Module({
    imports: [ /* the Module containing JwtService */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/neighborpil/Desktop/codes/GitRepository/nodejs_study_finishNodejsWith10projecs/fastcampus-nestjs-ch-1/node_modules/@nestjs/core/injector/injector.js:247:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Injector.resolveComponentInstance (/Users/neighborpil/Desktop/codes/GitRepository/nodejs_study_finishNodejsWith10projecs/fastcampus-nestjs-ch-1/node_modules/@nestjs/core/injector/injector.js:200:33)
    at resolveParam (/Users/neighborpil/Desktop/codes/GitRepository/nodejs_study_finishNodejsWith10projecs/fastcampus-nestjs-ch-1/node_modules/@nestjs/core/injector/injector.js:120:38)
    at async Promise.all (index 1)
    at Injector.resolveConstructorParams (/Users/neighborpil/Desktop/codes/GitRepository/nodejs_study_finishNodejsWith10projecs/fastcampus-nestjs-ch-1/node_modules/@nestjs/core/injector/injector.js:135:27)
    at Injector.loadInstance (/Users/neighborpil/Desktop/codes/GitRepository/nodejs_study_finishNodejsWith10projecs/fastcampus-nestjs-ch-1/node_modules/@nestjs/core/injector/injector.js:61:13)
    at Injector.loadInjectable (/Users/neighborpil/Desktop/codes/GitRepository/nodejs_study_finishNodejsWith10projecs/fastcampus-nestjs-ch-1/node_modules/@nestjs/core/injector/injector.js:84:9)
    at /Users/neighborpil/Desktop/codes/GitRepository/nodejs_study_finishNodejsWith10projecs/fastcampus-nestjs-ch-1/node_modules/@nestjs/core/injector/instance-loader.js:80:13
    at async Promise.all (index 0)

JwtAuthGuard는 다음과 같습니다.

import { Reflector } from '@nestjs/core';
import { ExecutionContext, Inject, Injectable, Logger, LoggerService, UnauthorizedException } from '@nestjs/common';
import { JwtService } from '@nestjs/jwt';
import { AuthGuard } from '@nestjs/passport';
import { Observable } from 'rxjs';
import { IS_PUBLIC_KEY } from 'src/common/decorator/public.decorator';
import { UserService } from 'src/user/user.service';

@Injectable()
export class JwtAuthGuard extends AuthGuard('jwt') {
  constructor(
    private reflector: Reflector,
    private jwtService: JwtService,
    private userService: UserService,
  ) {
    super();
  }

  canActivate(context: ExecutionContext): boolean | Promise<boolean> | Observable<boolean> {
    const isPublic = this.reflector.getAllAndOverride<boolean>(IS_PUBLIC_KEY, [
      context.getHandler(),
      context.getClass(),
    ]);
    if (isPublic) {
      return true;
    }

    const http = context.switchToHttp();
    const { url, headers } = http.getRequest<Request>();

    const authorization = headers['authorization'];
    if (!authorization) throw new UnauthorizedException();
    if (!authorization.includes('Bearer')) throw new UnauthorizedException();

    const token = /Bearer\s(.+)/.exec(authorization)[1];
    if (!token) throw new UnauthorizedException('accessToken is required');

    const decoded = this.jwtService.decode(token);

    // refresh token을 accessToken으로 사용하려고 할 때
    if (url !== '/api/auth/refresh' && decoded['tokenType'] === 'refresh') {
      console.error('accessToken is required');
      throw new UnauthorizedException();
    }

    return super.canActivate(context);
  }
}

뭐가 문제인걸까요? ㅠㅠ

**Comment by neighborpil** [comment]
UserController쪽에서

@UseGuards(JwtAuthGuard)

이게 켜져 있어서 안되는 문제였습니다
닫겠습니다
